// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module SodorTile(
  input         clock,
                reset,
                auto_buffer_in_a_valid,
  input  [2:0]  auto_buffer_in_a_bits_opcode,
                auto_buffer_in_a_bits_param,
                auto_buffer_in_a_bits_size,
  input  [5:0]  auto_buffer_in_a_bits_source,
  input  [31:0] auto_buffer_in_a_bits_address,
  input  [3:0]  auto_buffer_in_a_bits_mask,
  input  [31:0] auto_buffer_in_a_bits_data,
  input         auto_buffer_in_d_ready,
                auto_buffer_out_a_ready,
                auto_buffer_out_d_valid,
  input  [2:0]  auto_buffer_out_d_bits_opcode,
  input  [1:0]  auto_buffer_out_d_bits_param,
  input  [3:0]  auto_buffer_out_d_bits_size,
  input         auto_buffer_out_d_bits_source,
                auto_buffer_out_d_bits_sink,
                auto_buffer_out_d_bits_denied,
  input  [31:0] auto_buffer_out_d_bits_data,
  input         auto_buffer_out_d_bits_corrupt,
                auto_int_local_in_2_0,
                auto_int_local_in_1_0,
                auto_int_local_in_1_1,
                auto_int_local_in_0_0,
                auto_hartid_in,
  output        auto_buffer_in_a_ready,
                auto_buffer_in_d_valid,
  output [2:0]  auto_buffer_in_d_bits_opcode,
                auto_buffer_in_d_bits_size,
  output [5:0]  auto_buffer_in_d_bits_source,
  output [31:0] auto_buffer_in_d_bits_data,
  output        auto_buffer_out_a_valid,
  output [2:0]  auto_buffer_out_a_bits_opcode,
                auto_buffer_out_a_bits_param,
  output [3:0]  auto_buffer_out_a_bits_size,
  output        auto_buffer_out_a_bits_source,
  output [31:0] auto_buffer_out_a_bits_address,
  output [3:0]  auto_buffer_out_a_bits_mask,
  output [31:0] auto_buffer_out_a_bits_data,
  output        auto_buffer_out_a_bits_corrupt,
                auto_buffer_out_d_ready
);

  wire        _scratchpadAdapter_io_slavePort_resp_valid;	// @[sodor_tile.scala:194:33]
  wire [31:0] _scratchpadAdapter_io_slavePort_resp_bits_data_raw;	// @[sodor_tile.scala:194:33]
  wire        _scratchpadAdapter_io_memPort_req_valid;	// @[sodor_tile.scala:194:33]
  wire [31:0] _scratchpadAdapter_io_memPort_req_bits_addr;	// @[sodor_tile.scala:194:33]
  wire [31:0] _scratchpadAdapter_io_memPort_req_bits_data;	// @[sodor_tile.scala:194:33]
  wire        _scratchpadAdapter_io_memPort_req_bits_fcn;	// @[sodor_tile.scala:194:33]
  wire [2:0]  _scratchpadAdapter_io_memPort_req_bits_typ;	// @[sodor_tile.scala:194:33]
  wire        _tile_io_debug_port_resp_valid;	// @[sodor_tile.scala:191:20]
  wire [31:0] _tile_io_debug_port_resp_bits_data;	// @[sodor_tile.scala:191:20]
  wire        _tile_io_master_port_0_req_valid;	// @[sodor_tile.scala:191:20]
  wire [31:0] _tile_io_master_port_0_req_bits_addr;	// @[sodor_tile.scala:191:20]
  wire [31:0] _tile_io_master_port_0_req_bits_data;	// @[sodor_tile.scala:191:20]
  wire        _tile_io_master_port_0_req_bits_fcn;	// @[sodor_tile.scala:191:20]
  wire [2:0]  _tile_io_master_port_0_req_bits_typ;	// @[sodor_tile.scala:191:20]
  wire        _tile_io_master_port_1_req_valid;	// @[sodor_tile.scala:191:20]
  wire [31:0] _tile_io_master_port_1_req_bits_addr;	// @[sodor_tile.scala:191:20]
  wire [31:0] _tile_io_master_port_1_req_bits_data;	// @[sodor_tile.scala:191:20]
  wire        _tile_io_master_port_1_req_bits_fcn;	// @[sodor_tile.scala:191:20]
  wire [2:0]  _tile_io_master_port_1_req_bits_typ;	// @[sodor_tile.scala:191:20]
  wire        _dmaster_adapter_auto_out_a_valid;	// @[sodor_tile.scala:144:35]
  wire [2:0]  _dmaster_adapter_auto_out_a_bits_opcode;	// @[sodor_tile.scala:144:35]
  wire [2:0]  _dmaster_adapter_auto_out_a_bits_param;	// @[sodor_tile.scala:144:35]
  wire [3:0]  _dmaster_adapter_auto_out_a_bits_size;	// @[sodor_tile.scala:144:35]
  wire        _dmaster_adapter_auto_out_a_bits_source;	// @[sodor_tile.scala:144:35]
  wire [31:0] _dmaster_adapter_auto_out_a_bits_address;	// @[sodor_tile.scala:144:35]
  wire [3:0]  _dmaster_adapter_auto_out_a_bits_mask;	// @[sodor_tile.scala:144:35]
  wire [31:0] _dmaster_adapter_auto_out_a_bits_data;	// @[sodor_tile.scala:144:35]
  wire        _dmaster_adapter_auto_out_a_bits_corrupt;	// @[sodor_tile.scala:144:35]
  wire        _dmaster_adapter_auto_out_d_ready;	// @[sodor_tile.scala:144:35]
  wire        _dmaster_adapter_io_dport_resp_valid;	// @[sodor_tile.scala:144:35]
  wire [31:0] _dmaster_adapter_io_dport_resp_bits_data;	// @[sodor_tile.scala:144:35]
  wire        _imaster_adapter_auto_out_a_valid;	// @[sodor_tile.scala:142:73]
  wire [2:0]  _imaster_adapter_auto_out_a_bits_opcode;	// @[sodor_tile.scala:142:73]
  wire [2:0]  _imaster_adapter_auto_out_a_bits_param;	// @[sodor_tile.scala:142:73]
  wire [3:0]  _imaster_adapter_auto_out_a_bits_size;	// @[sodor_tile.scala:142:73]
  wire        _imaster_adapter_auto_out_a_bits_source;	// @[sodor_tile.scala:142:73]
  wire [31:0] _imaster_adapter_auto_out_a_bits_address;	// @[sodor_tile.scala:142:73]
  wire [3:0]  _imaster_adapter_auto_out_a_bits_mask;	// @[sodor_tile.scala:142:73]
  wire [31:0] _imaster_adapter_auto_out_a_bits_data;	// @[sodor_tile.scala:142:73]
  wire        _imaster_adapter_auto_out_a_bits_corrupt;	// @[sodor_tile.scala:142:73]
  wire        _imaster_adapter_auto_out_d_ready;	// @[sodor_tile.scala:142:73]
  wire        _imaster_adapter_io_dport_resp_valid;	// @[sodor_tile.scala:142:73]
  wire [31:0] _imaster_adapter_io_dport_resp_bits_data;	// @[sodor_tile.scala:142:73]
  wire        _fragmenter_auto_out_a_valid;	// @[Fragmenter.scala:335:34]
  wire [2:0]  _fragmenter_auto_out_a_bits_opcode;	// @[Fragmenter.scala:335:34]
  wire [2:0]  _fragmenter_auto_out_a_bits_param;	// @[Fragmenter.scala:335:34]
  wire [1:0]  _fragmenter_auto_out_a_bits_size;	// @[Fragmenter.scala:335:34]
  wire [11:0] _fragmenter_auto_out_a_bits_source;	// @[Fragmenter.scala:335:34]
  wire [31:0] _fragmenter_auto_out_a_bits_address;	// @[Fragmenter.scala:335:34]
  wire [3:0]  _fragmenter_auto_out_a_bits_mask;	// @[Fragmenter.scala:335:34]
  wire [31:0] _fragmenter_auto_out_a_bits_data;	// @[Fragmenter.scala:335:34]
  wire        _fragmenter_auto_out_d_ready;	// @[Fragmenter.scala:335:34]
  wire        _dtim_adapter_auto_in_a_ready;	// @[sodor_tile.scala:134:15]
  wire        _dtim_adapter_auto_in_d_valid;	// @[sodor_tile.scala:134:15]
  wire [2:0]  _dtim_adapter_auto_in_d_bits_opcode;	// @[sodor_tile.scala:134:15]
  wire [1:0]  _dtim_adapter_auto_in_d_bits_size;	// @[sodor_tile.scala:134:15]
  wire [11:0] _dtim_adapter_auto_in_d_bits_source;	// @[sodor_tile.scala:134:15]
  wire [31:0] _dtim_adapter_auto_in_d_bits_data;	// @[sodor_tile.scala:134:15]
  wire        _dtim_adapter_io_dmem_req_valid;	// @[sodor_tile.scala:134:15]
  wire [31:0] _dtim_adapter_io_dmem_req_bits_addr;	// @[sodor_tile.scala:134:15]
  wire [4:0]  _dtim_adapter_io_dmem_req_bits_cmd;	// @[sodor_tile.scala:134:15]
  wire [1:0]  _dtim_adapter_io_dmem_req_bits_size;	// @[sodor_tile.scala:134:15]
  wire        _dtim_adapter_io_dmem_s1_kill;	// @[sodor_tile.scala:134:15]
  wire [31:0] _dtim_adapter_io_dmem_s1_data_data;	// @[sodor_tile.scala:134:15]
  wire        _intXbar_auto_int_out_0;	// @[BaseTile.scala:225:37]
  wire        _intXbar_auto_int_out_1;	// @[BaseTile.scala:225:37]
  wire        _intXbar_auto_int_out_2;	// @[BaseTile.scala:225:37]
  wire        _intXbar_auto_int_out_3;	// @[BaseTile.scala:225:37]
  wire        _tlMasterXbar_auto_in_1_a_ready;	// @[BaseTile.scala:223:42]
  wire        _tlMasterXbar_auto_in_1_d_valid;	// @[BaseTile.scala:223:42]
  wire [2:0]  _tlMasterXbar_auto_in_1_d_bits_opcode;	// @[BaseTile.scala:223:42]
  wire [1:0]  _tlMasterXbar_auto_in_1_d_bits_param;	// @[BaseTile.scala:223:42]
  wire [3:0]  _tlMasterXbar_auto_in_1_d_bits_size;	// @[BaseTile.scala:223:42]
  wire        _tlMasterXbar_auto_in_1_d_bits_sink;	// @[BaseTile.scala:223:42]
  wire        _tlMasterXbar_auto_in_1_d_bits_denied;	// @[BaseTile.scala:223:42]
  wire [31:0] _tlMasterXbar_auto_in_1_d_bits_data;	// @[BaseTile.scala:223:42]
  wire        _tlMasterXbar_auto_in_1_d_bits_corrupt;	// @[BaseTile.scala:223:42]
  wire        _tlMasterXbar_auto_in_0_a_ready;	// @[BaseTile.scala:223:42]
  wire        _tlMasterXbar_auto_in_0_d_valid;	// @[BaseTile.scala:223:42]
  wire [2:0]  _tlMasterXbar_auto_in_0_d_bits_opcode;	// @[BaseTile.scala:223:42]
  wire [1:0]  _tlMasterXbar_auto_in_0_d_bits_param;	// @[BaseTile.scala:223:42]
  wire [3:0]  _tlMasterXbar_auto_in_0_d_bits_size;	// @[BaseTile.scala:223:42]
  wire        _tlMasterXbar_auto_in_0_d_bits_sink;	// @[BaseTile.scala:223:42]
  wire        _tlMasterXbar_auto_in_0_d_bits_denied;	// @[BaseTile.scala:223:42]
  wire [31:0] _tlMasterXbar_auto_in_0_d_bits_data;	// @[BaseTile.scala:223:42]
  wire        _tlMasterXbar_auto_in_0_d_bits_corrupt;	// @[BaseTile.scala:223:42]
  TLXbar_6 tlMasterXbar (	// @[BaseTile.scala:223:42]
    .clock                    (clock),
    .reset                    (reset),
    .auto_in_1_a_valid        (_dmaster_adapter_auto_out_a_valid),	// @[sodor_tile.scala:144:35]
    .auto_in_1_a_bits_opcode  (_dmaster_adapter_auto_out_a_bits_opcode),	// @[sodor_tile.scala:144:35]
    .auto_in_1_a_bits_param   (_dmaster_adapter_auto_out_a_bits_param),	// @[sodor_tile.scala:144:35]
    .auto_in_1_a_bits_size    (_dmaster_adapter_auto_out_a_bits_size),	// @[sodor_tile.scala:144:35]
    .auto_in_1_a_bits_source  (_dmaster_adapter_auto_out_a_bits_source),	// @[sodor_tile.scala:144:35]
    .auto_in_1_a_bits_address (_dmaster_adapter_auto_out_a_bits_address),	// @[sodor_tile.scala:144:35]
    .auto_in_1_a_bits_mask    (_dmaster_adapter_auto_out_a_bits_mask),	// @[sodor_tile.scala:144:35]
    .auto_in_1_a_bits_data    (_dmaster_adapter_auto_out_a_bits_data),	// @[sodor_tile.scala:144:35]
    .auto_in_1_a_bits_corrupt (_dmaster_adapter_auto_out_a_bits_corrupt),	// @[sodor_tile.scala:144:35]
    .auto_in_1_d_ready        (_dmaster_adapter_auto_out_d_ready),	// @[sodor_tile.scala:144:35]
    .auto_in_0_a_valid        (_imaster_adapter_auto_out_a_valid),	// @[sodor_tile.scala:142:73]
    .auto_in_0_a_bits_opcode  (_imaster_adapter_auto_out_a_bits_opcode),	// @[sodor_tile.scala:142:73]
    .auto_in_0_a_bits_param   (_imaster_adapter_auto_out_a_bits_param),	// @[sodor_tile.scala:142:73]
    .auto_in_0_a_bits_size    (_imaster_adapter_auto_out_a_bits_size),	// @[sodor_tile.scala:142:73]
    .auto_in_0_a_bits_source  (_imaster_adapter_auto_out_a_bits_source),	// @[sodor_tile.scala:142:73]
    .auto_in_0_a_bits_address (_imaster_adapter_auto_out_a_bits_address),	// @[sodor_tile.scala:142:73]
    .auto_in_0_a_bits_mask    (_imaster_adapter_auto_out_a_bits_mask),	// @[sodor_tile.scala:142:73]
    .auto_in_0_a_bits_data    (_imaster_adapter_auto_out_a_bits_data),	// @[sodor_tile.scala:142:73]
    .auto_in_0_a_bits_corrupt (_imaster_adapter_auto_out_a_bits_corrupt),	// @[sodor_tile.scala:142:73]
    .auto_in_0_d_ready        (_imaster_adapter_auto_out_d_ready),	// @[sodor_tile.scala:142:73]
    .auto_out_a_ready         (auto_buffer_out_a_ready),
    .auto_out_d_valid         (auto_buffer_out_d_valid),
    .auto_out_d_bits_opcode   (auto_buffer_out_d_bits_opcode),
    .auto_out_d_bits_param    (auto_buffer_out_d_bits_param),
    .auto_out_d_bits_size     (auto_buffer_out_d_bits_size),
    .auto_out_d_bits_source   (auto_buffer_out_d_bits_source),
    .auto_out_d_bits_sink     (auto_buffer_out_d_bits_sink),
    .auto_out_d_bits_denied   (auto_buffer_out_d_bits_denied),
    .auto_out_d_bits_data     (auto_buffer_out_d_bits_data),
    .auto_out_d_bits_corrupt  (auto_buffer_out_d_bits_corrupt),
    .auto_in_1_a_ready        (_tlMasterXbar_auto_in_1_a_ready),
    .auto_in_1_d_valid        (_tlMasterXbar_auto_in_1_d_valid),
    .auto_in_1_d_bits_opcode  (_tlMasterXbar_auto_in_1_d_bits_opcode),
    .auto_in_1_d_bits_param   (_tlMasterXbar_auto_in_1_d_bits_param),
    .auto_in_1_d_bits_size    (_tlMasterXbar_auto_in_1_d_bits_size),
    .auto_in_1_d_bits_sink    (_tlMasterXbar_auto_in_1_d_bits_sink),
    .auto_in_1_d_bits_denied  (_tlMasterXbar_auto_in_1_d_bits_denied),
    .auto_in_1_d_bits_data    (_tlMasterXbar_auto_in_1_d_bits_data),
    .auto_in_1_d_bits_corrupt (_tlMasterXbar_auto_in_1_d_bits_corrupt),
    .auto_in_0_a_ready        (_tlMasterXbar_auto_in_0_a_ready),
    .auto_in_0_d_valid        (_tlMasterXbar_auto_in_0_d_valid),
    .auto_in_0_d_bits_opcode  (_tlMasterXbar_auto_in_0_d_bits_opcode),
    .auto_in_0_d_bits_param   (_tlMasterXbar_auto_in_0_d_bits_param),
    .auto_in_0_d_bits_size    (_tlMasterXbar_auto_in_0_d_bits_size),
    .auto_in_0_d_bits_sink    (_tlMasterXbar_auto_in_0_d_bits_sink),
    .auto_in_0_d_bits_denied  (_tlMasterXbar_auto_in_0_d_bits_denied),
    .auto_in_0_d_bits_data    (_tlMasterXbar_auto_in_0_d_bits_data),
    .auto_in_0_d_bits_corrupt (_tlMasterXbar_auto_in_0_d_bits_corrupt),
    .auto_out_a_valid         (auto_buffer_out_a_valid),
    .auto_out_a_bits_opcode   (auto_buffer_out_a_bits_opcode),
    .auto_out_a_bits_param    (auto_buffer_out_a_bits_param),
    .auto_out_a_bits_size     (auto_buffer_out_a_bits_size),
    .auto_out_a_bits_source   (auto_buffer_out_a_bits_source),
    .auto_out_a_bits_address  (auto_buffer_out_a_bits_address),
    .auto_out_a_bits_mask     (auto_buffer_out_a_bits_mask),
    .auto_out_a_bits_data     (auto_buffer_out_a_bits_data),
    .auto_out_a_bits_corrupt  (auto_buffer_out_a_bits_corrupt),
    .auto_out_d_ready         (auto_buffer_out_d_ready)
  );
  IntXbar_1 intXbar (	// @[BaseTile.scala:225:37]
    .auto_int_in_2_0 (auto_int_local_in_2_0),
    .auto_int_in_1_0 (auto_int_local_in_1_0),
    .auto_int_in_1_1 (auto_int_local_in_1_1),
    .auto_int_in_0_0 (auto_int_local_in_0_0),
    .auto_int_out_0  (_intXbar_auto_int_out_0),
    .auto_int_out_1  (_intXbar_auto_int_out_1),
    .auto_int_out_2  (_intXbar_auto_int_out_2),
    .auto_int_out_3  (_intXbar_auto_int_out_3)
  );
  ScratchpadSlavePort dtim_adapter (	// @[sodor_tile.scala:134:15]
    .clock                      (clock),
    .reset                      (reset),
    .auto_in_a_valid            (_fragmenter_auto_out_a_valid),	// @[Fragmenter.scala:335:34]
    .auto_in_a_bits_opcode      (_fragmenter_auto_out_a_bits_opcode),	// @[Fragmenter.scala:335:34]
    .auto_in_a_bits_param       (_fragmenter_auto_out_a_bits_param),	// @[Fragmenter.scala:335:34]
    .auto_in_a_bits_size        (_fragmenter_auto_out_a_bits_size),	// @[Fragmenter.scala:335:34]
    .auto_in_a_bits_source      (_fragmenter_auto_out_a_bits_source),	// @[Fragmenter.scala:335:34]
    .auto_in_a_bits_address     (_fragmenter_auto_out_a_bits_address),	// @[Fragmenter.scala:335:34]
    .auto_in_a_bits_mask        (_fragmenter_auto_out_a_bits_mask),	// @[Fragmenter.scala:335:34]
    .auto_in_a_bits_data        (_fragmenter_auto_out_a_bits_data),	// @[Fragmenter.scala:335:34]
    .auto_in_d_ready            (_fragmenter_auto_out_d_ready),	// @[Fragmenter.scala:335:34]
    .io_dmem_resp_valid         (_scratchpadAdapter_io_slavePort_resp_valid),	// @[sodor_tile.scala:194:33]
    .io_dmem_resp_bits_data_raw (_scratchpadAdapter_io_slavePort_resp_bits_data_raw),	// @[sodor_tile.scala:194:33]
    .auto_in_a_ready            (_dtim_adapter_auto_in_a_ready),
    .auto_in_d_valid            (_dtim_adapter_auto_in_d_valid),
    .auto_in_d_bits_opcode      (_dtim_adapter_auto_in_d_bits_opcode),
    .auto_in_d_bits_size        (_dtim_adapter_auto_in_d_bits_size),
    .auto_in_d_bits_source      (_dtim_adapter_auto_in_d_bits_source),
    .auto_in_d_bits_data        (_dtim_adapter_auto_in_d_bits_data),
    .io_dmem_req_valid          (_dtim_adapter_io_dmem_req_valid),
    .io_dmem_req_bits_addr      (_dtim_adapter_io_dmem_req_bits_addr),
    .io_dmem_req_bits_cmd       (_dtim_adapter_io_dmem_req_bits_cmd),
    .io_dmem_req_bits_size      (_dtim_adapter_io_dmem_req_bits_size),
    .io_dmem_s1_kill            (_dtim_adapter_io_dmem_s1_kill),
    .io_dmem_s1_data_data       (_dtim_adapter_io_dmem_s1_data_data)
  );
  TLFragmenter_7 fragmenter (	// @[Fragmenter.scala:335:34]
    .clock                   (clock),
    .reset                   (reset),
    .auto_in_a_valid         (auto_buffer_in_a_valid),
    .auto_in_a_bits_opcode   (auto_buffer_in_a_bits_opcode),
    .auto_in_a_bits_param    (auto_buffer_in_a_bits_param),
    .auto_in_a_bits_size     (auto_buffer_in_a_bits_size),
    .auto_in_a_bits_source   (auto_buffer_in_a_bits_source),
    .auto_in_a_bits_address  (auto_buffer_in_a_bits_address),
    .auto_in_a_bits_mask     (auto_buffer_in_a_bits_mask),
    .auto_in_a_bits_data     (auto_buffer_in_a_bits_data),
    .auto_in_d_ready         (auto_buffer_in_d_ready),
    .auto_out_a_ready        (_dtim_adapter_auto_in_a_ready),	// @[sodor_tile.scala:134:15]
    .auto_out_d_valid        (_dtim_adapter_auto_in_d_valid),	// @[sodor_tile.scala:134:15]
    .auto_out_d_bits_opcode  (_dtim_adapter_auto_in_d_bits_opcode),	// @[sodor_tile.scala:134:15]
    .auto_out_d_bits_size    (_dtim_adapter_auto_in_d_bits_size),	// @[sodor_tile.scala:134:15]
    .auto_out_d_bits_source  (_dtim_adapter_auto_in_d_bits_source),	// @[sodor_tile.scala:134:15]
    .auto_out_d_bits_data    (_dtim_adapter_auto_in_d_bits_data),	// @[sodor_tile.scala:134:15]
    .auto_in_a_ready         (auto_buffer_in_a_ready),
    .auto_in_d_valid         (auto_buffer_in_d_valid),
    .auto_in_d_bits_opcode   (auto_buffer_in_d_bits_opcode),
    .auto_in_d_bits_size     (auto_buffer_in_d_bits_size),
    .auto_in_d_bits_source   (auto_buffer_in_d_bits_source),
    .auto_in_d_bits_data     (auto_buffer_in_d_bits_data),
    .auto_out_a_valid        (_fragmenter_auto_out_a_valid),
    .auto_out_a_bits_opcode  (_fragmenter_auto_out_a_bits_opcode),
    .auto_out_a_bits_param   (_fragmenter_auto_out_a_bits_param),
    .auto_out_a_bits_size    (_fragmenter_auto_out_a_bits_size),
    .auto_out_a_bits_source  (_fragmenter_auto_out_a_bits_source),
    .auto_out_a_bits_address (_fragmenter_auto_out_a_bits_address),
    .auto_out_a_bits_mask    (_fragmenter_auto_out_a_bits_mask),
    .auto_out_a_bits_data    (_fragmenter_auto_out_a_bits_data),
    .auto_out_d_ready        (_fragmenter_auto_out_d_ready)
  );
  SodorMasterAdapter imaster_adapter (	// @[sodor_tile.scala:142:73]
    .clock                   (clock),
    .reset                   (reset),
    .auto_out_a_ready        (_tlMasterXbar_auto_in_0_a_ready),	// @[BaseTile.scala:223:42]
    .auto_out_d_valid        (_tlMasterXbar_auto_in_0_d_valid),	// @[BaseTile.scala:223:42]
    .auto_out_d_bits_opcode  (_tlMasterXbar_auto_in_0_d_bits_opcode),	// @[BaseTile.scala:223:42]
    .auto_out_d_bits_param   (_tlMasterXbar_auto_in_0_d_bits_param),	// @[BaseTile.scala:223:42]
    .auto_out_d_bits_size    (_tlMasterXbar_auto_in_0_d_bits_size),	// @[BaseTile.scala:223:42]
    .auto_out_d_bits_sink    (_tlMasterXbar_auto_in_0_d_bits_sink),	// @[BaseTile.scala:223:42]
    .auto_out_d_bits_denied  (_tlMasterXbar_auto_in_0_d_bits_denied),	// @[BaseTile.scala:223:42]
    .auto_out_d_bits_data    (_tlMasterXbar_auto_in_0_d_bits_data),	// @[BaseTile.scala:223:42]
    .auto_out_d_bits_corrupt (_tlMasterXbar_auto_in_0_d_bits_corrupt),	// @[BaseTile.scala:223:42]
    .io_dport_req_valid      (_tile_io_master_port_1_req_valid),	// @[sodor_tile.scala:191:20]
    .io_dport_req_bits_addr  (_tile_io_master_port_1_req_bits_addr),	// @[sodor_tile.scala:191:20]
    .io_dport_req_bits_data  (_tile_io_master_port_1_req_bits_data),	// @[sodor_tile.scala:191:20]
    .io_dport_req_bits_fcn   (_tile_io_master_port_1_req_bits_fcn),	// @[sodor_tile.scala:191:20]
    .io_dport_req_bits_typ   (_tile_io_master_port_1_req_bits_typ),	// @[sodor_tile.scala:191:20]
    .auto_out_a_valid        (_imaster_adapter_auto_out_a_valid),
    .auto_out_a_bits_opcode  (_imaster_adapter_auto_out_a_bits_opcode),
    .auto_out_a_bits_param   (_imaster_adapter_auto_out_a_bits_param),
    .auto_out_a_bits_size    (_imaster_adapter_auto_out_a_bits_size),
    .auto_out_a_bits_source  (_imaster_adapter_auto_out_a_bits_source),
    .auto_out_a_bits_address (_imaster_adapter_auto_out_a_bits_address),
    .auto_out_a_bits_mask    (_imaster_adapter_auto_out_a_bits_mask),
    .auto_out_a_bits_data    (_imaster_adapter_auto_out_a_bits_data),
    .auto_out_a_bits_corrupt (_imaster_adapter_auto_out_a_bits_corrupt),
    .auto_out_d_ready        (_imaster_adapter_auto_out_d_ready),
    .io_dport_resp_valid     (_imaster_adapter_io_dport_resp_valid),
    .io_dport_resp_bits_data (_imaster_adapter_io_dport_resp_bits_data)
  );
  SodorMasterAdapter dmaster_adapter (	// @[sodor_tile.scala:144:35]
    .clock                   (clock),
    .reset                   (reset),
    .auto_out_a_ready        (_tlMasterXbar_auto_in_1_a_ready),	// @[BaseTile.scala:223:42]
    .auto_out_d_valid        (_tlMasterXbar_auto_in_1_d_valid),	// @[BaseTile.scala:223:42]
    .auto_out_d_bits_opcode  (_tlMasterXbar_auto_in_1_d_bits_opcode),	// @[BaseTile.scala:223:42]
    .auto_out_d_bits_param   (_tlMasterXbar_auto_in_1_d_bits_param),	// @[BaseTile.scala:223:42]
    .auto_out_d_bits_size    (_tlMasterXbar_auto_in_1_d_bits_size),	// @[BaseTile.scala:223:42]
    .auto_out_d_bits_sink    (_tlMasterXbar_auto_in_1_d_bits_sink),	// @[BaseTile.scala:223:42]
    .auto_out_d_bits_denied  (_tlMasterXbar_auto_in_1_d_bits_denied),	// @[BaseTile.scala:223:42]
    .auto_out_d_bits_data    (_tlMasterXbar_auto_in_1_d_bits_data),	// @[BaseTile.scala:223:42]
    .auto_out_d_bits_corrupt (_tlMasterXbar_auto_in_1_d_bits_corrupt),	// @[BaseTile.scala:223:42]
    .io_dport_req_valid      (_tile_io_master_port_0_req_valid),	// @[sodor_tile.scala:191:20]
    .io_dport_req_bits_addr  (_tile_io_master_port_0_req_bits_addr),	// @[sodor_tile.scala:191:20]
    .io_dport_req_bits_data  (_tile_io_master_port_0_req_bits_data),	// @[sodor_tile.scala:191:20]
    .io_dport_req_bits_fcn   (_tile_io_master_port_0_req_bits_fcn),	// @[sodor_tile.scala:191:20]
    .io_dport_req_bits_typ   (_tile_io_master_port_0_req_bits_typ),	// @[sodor_tile.scala:191:20]
    .auto_out_a_valid        (_dmaster_adapter_auto_out_a_valid),
    .auto_out_a_bits_opcode  (_dmaster_adapter_auto_out_a_bits_opcode),
    .auto_out_a_bits_param   (_dmaster_adapter_auto_out_a_bits_param),
    .auto_out_a_bits_size    (_dmaster_adapter_auto_out_a_bits_size),
    .auto_out_a_bits_source  (_dmaster_adapter_auto_out_a_bits_source),
    .auto_out_a_bits_address (_dmaster_adapter_auto_out_a_bits_address),
    .auto_out_a_bits_mask    (_dmaster_adapter_auto_out_a_bits_mask),
    .auto_out_a_bits_data    (_dmaster_adapter_auto_out_a_bits_data),
    .auto_out_a_bits_corrupt (_dmaster_adapter_auto_out_a_bits_corrupt),
    .auto_out_d_ready        (_dmaster_adapter_auto_out_d_ready),
    .io_dport_resp_valid     (_dmaster_adapter_io_dport_resp_valid),
    .io_dport_resp_bits_data (_dmaster_adapter_io_dport_resp_bits_data)
  );
  SodorInternalTile tile (	// @[sodor_tile.scala:191:20]
    .clock                           (clock),
    .reset                           (reset),
    .io_debug_port_req_valid         (_scratchpadAdapter_io_memPort_req_valid),	// @[sodor_tile.scala:194:33]
    .io_debug_port_req_bits_addr     (_scratchpadAdapter_io_memPort_req_bits_addr),	// @[sodor_tile.scala:194:33]
    .io_debug_port_req_bits_data     (_scratchpadAdapter_io_memPort_req_bits_data),	// @[sodor_tile.scala:194:33]
    .io_debug_port_req_bits_fcn      (_scratchpadAdapter_io_memPort_req_bits_fcn),	// @[sodor_tile.scala:194:33]
    .io_debug_port_req_bits_typ      (_scratchpadAdapter_io_memPort_req_bits_typ),	// @[sodor_tile.scala:194:33]
    .io_master_port_0_resp_valid     (_dmaster_adapter_io_dport_resp_valid),	// @[sodor_tile.scala:144:35]
    .io_master_port_0_resp_bits_data (_dmaster_adapter_io_dport_resp_bits_data),	// @[sodor_tile.scala:144:35]
    .io_master_port_1_resp_valid     (_imaster_adapter_io_dport_resp_valid),	// @[sodor_tile.scala:142:73]
    .io_master_port_1_resp_bits_data (_imaster_adapter_io_dport_resp_bits_data),	// @[sodor_tile.scala:142:73]
    .io_interrupt_debug              (_intXbar_auto_int_out_0),	// @[BaseTile.scala:225:37]
    .io_interrupt_mtip               (_intXbar_auto_int_out_2),	// @[BaseTile.scala:225:37]
    .io_interrupt_msip               (_intXbar_auto_int_out_1),	// @[BaseTile.scala:225:37]
    .io_interrupt_meip               (_intXbar_auto_int_out_3),	// @[BaseTile.scala:225:37]
    .io_hartid                       (auto_hartid_in),
    .io_debug_port_resp_valid        (_tile_io_debug_port_resp_valid),
    .io_debug_port_resp_bits_data    (_tile_io_debug_port_resp_bits_data),
    .io_master_port_0_req_valid      (_tile_io_master_port_0_req_valid),
    .io_master_port_0_req_bits_addr  (_tile_io_master_port_0_req_bits_addr),
    .io_master_port_0_req_bits_data  (_tile_io_master_port_0_req_bits_data),
    .io_master_port_0_req_bits_fcn   (_tile_io_master_port_0_req_bits_fcn),
    .io_master_port_0_req_bits_typ   (_tile_io_master_port_0_req_bits_typ),
    .io_master_port_1_req_valid      (_tile_io_master_port_1_req_valid),
    .io_master_port_1_req_bits_addr  (_tile_io_master_port_1_req_bits_addr),
    .io_master_port_1_req_bits_data  (_tile_io_master_port_1_req_bits_data),
    .io_master_port_1_req_bits_fcn   (_tile_io_master_port_1_req_bits_fcn),
    .io_master_port_1_req_bits_typ   (_tile_io_master_port_1_req_bits_typ)
  );
  SodorScratchpadAdapter scratchpadAdapter (	// @[sodor_tile.scala:194:33]
    .clock                           (clock),
    .reset                           (reset),
    .io_slavePort_req_valid          (_dtim_adapter_io_dmem_req_valid),	// @[sodor_tile.scala:134:15]
    .io_slavePort_req_bits_addr      (_dtim_adapter_io_dmem_req_bits_addr),	// @[sodor_tile.scala:134:15]
    .io_slavePort_req_bits_cmd       (_dtim_adapter_io_dmem_req_bits_cmd),	// @[sodor_tile.scala:134:15]
    .io_slavePort_req_bits_size      (_dtim_adapter_io_dmem_req_bits_size),	// @[sodor_tile.scala:134:15]
    .io_slavePort_s1_kill            (_dtim_adapter_io_dmem_s1_kill),	// @[sodor_tile.scala:134:15]
    .io_slavePort_s1_data_data       (_dtim_adapter_io_dmem_s1_data_data),	// @[sodor_tile.scala:134:15]
    .io_memPort_resp_valid           (_tile_io_debug_port_resp_valid),	// @[sodor_tile.scala:191:20]
    .io_memPort_resp_bits_data       (_tile_io_debug_port_resp_bits_data),	// @[sodor_tile.scala:191:20]
    .io_slavePort_resp_valid         (_scratchpadAdapter_io_slavePort_resp_valid),
    .io_slavePort_resp_bits_data_raw (_scratchpadAdapter_io_slavePort_resp_bits_data_raw),
    .io_memPort_req_valid            (_scratchpadAdapter_io_memPort_req_valid),
    .io_memPort_req_bits_addr        (_scratchpadAdapter_io_memPort_req_bits_addr),
    .io_memPort_req_bits_data        (_scratchpadAdapter_io_memPort_req_bits_data),
    .io_memPort_req_bits_fcn         (_scratchpadAdapter_io_memPort_req_bits_fcn),
    .io_memPort_req_bits_typ         (_scratchpadAdapter_io_memPort_req_bits_typ)
  );
endmodule

